### ISSUE TITLE
Figure out data streaming with jq

### ISSUE THREAD

**Issue by lukas-vlcek** [ViaQ/watches-cli#18]
There is [tutorial](https://github.com/ViaQ/watches-cli/blob/master/TUTORIAL.md) showing how to turn JSON output into CVS format using `jq` library. We need to find out if and how we can use [jq streaming](https://github.com/stedolan/jq/wiki/FAQ#streaming-json-parser) to handle huge data.

Also see https://github.com/stedolan/jq/wiki/Cookbook#processing-a-huge-json-array-of-items

**Comment by richm** [comment]
Don't we want watches to output csv directly?  Do we want users of watches to pipe the output to jq if they want csv output?

**Comment by lukas-vlcek** [comment]
This depends. Right now we know the "user" is pbench. The question is what format pbench can consume (and [it is not fully clear to me ATM](https://github.com/distributed-system-analysis/pbench/issues/396#issuecomment-268982398), it seems it could consume even JSON directly?). So if users can consume JSON then we are ready to go. If users need CSV then the question is if we need to implement it or shop elsewhere, I do not know how much resources jq need to process huge data but it seem to provide a lot of interesting functionality.

**Comment by lukas-vlcek** [comment]
Closing for now. We can re-open later if needed.
The first integration is for pbench and pbench post-processing scripts can perfectly work with any collection tool output format including JSON. See related ticket <https://github.com/distributed-system-analysis/pbench/issues/396>.
