### ISSUE TITLE
Add support for Python 3.x

### ISSUE THREAD

**Issue by lukas-vlcek** [ViaQ/watches-cli#34]
https://pypi.python.org/pypi/sixer

**Comment by richm** [comment]
This is how I set up sixer on F25: https://gist.github.com/richm/43f2256da50ffe4a8dff164788f4eb2d

This is the sixer report: https://gist.github.com/richm/3e97d48c6bb8f813fc34cf55a951cd26

**Comment by lukas-vlcek** [comment]
We probably also need to check tips here: https://wiki.python.org/moin/PortingPythonToPy3k

**Comment by lukas-vlcek** [comment]
FYI: The first issue is that we are [explicitly requiring `logging`](https://github.com/ViaQ/watches-cli/blob/77dd829f53d9663ff6343c08abe5b84c43c3497c/setup.py#L55). After I removed it I was able to get Python 2.7 test pass without issues. Test for Python 3.5 still fail but for different reason now (due to real incompatibilities between 2vs3).
